FeatureScript 2716;
import(path : "onshape/std/common.fs", version : "2716.0");

// GENERATED by gen_fs.py — Probe #42 hood scoop system. Edit the generator / feature parameters, not this file.
// Site frame fitted from the outer-hood scan near the owner's tested label location (APPROXIMATE, not a calibrated coordinate).
const SITE_O = vector(110.0000000, -340.0000000, 104.2237223) * millimeter;
const SITE_M = [[0.9996924, 0.0037769, 0.0245124], [0.0000000, 0.9883367, -0.1522845], [-0.0248017, 0.1522376, 0.9880327]] as Matrix;
const SAG_D = -0.0001481; const SAG_E = -0.0000129; const SAG_F = -0.0002852;   // local hood sag z = D x^2 + E x y + F y^2 (mm, mm^-1)

function sagZ(x is number, y is number) returns number { return SAG_D * x * x + SAG_E * x * y + SAG_F * y * y; }

function mkBox(context is Context, id is Id, x0 is number, y0 is number, z0 is number, x1 is number, y1 is number, z1 is number) returns Query
{
    fCuboid(context, id, { "corner1" : vector(x0, y0, z0) * millimeter, "corner2" : vector(x1, y1, z1) * millimeter });
    return qCreatedBy(id, EntityType.BODY);
}
function cylZ(context is Context, id is Id, cx is number, cy is number, z0 is number, z1 is number, d is number) returns Query
{
    fCylinder(context, id, { "topCenter" : vector(cx, cy, z1) * millimeter, "bottomCenter" : vector(cx, cy, z0) * millimeter, "radius" : d / 2 * millimeter });
    return qCreatedBy(id, EntityType.BODY);
}
function filletDir(context is Context, id is Id, body is Query, dir is Vector, r is number)
{
    opFillet(context, id, { "entities" : qParallelEdges(qOwnedByBody(body, EntityType.EDGE), dir), "radius" : r * millimeter });
}
// rounded-rectangle prism (corner radius on the vertical edges)
function rrBox(context is Context, id is Id, cx is number, cy is number, w is number, l is number, z0 is number, z1 is number, r is number) returns Query
{
    const b = mkBox(context, id + "b", cx - w / 2, cy - l / 2, z0, cx + w / 2, cy + l / 2, z1);
    if (r > 0) filletDir(context, id + "f", b, vector(0, 0, 1), r);
    return b;
}
// triangular prism along +x: polygon given as (y, z) points (mm), extruded from x0 by length
function wedgeX(context is Context, id is Id, x0 is number, length is number, pts is array) returns Query
{
    var sk = newSketchOnPlane(context, id + "sk", { "sketchPlane" : plane(vector(x0, 0, 0) * millimeter, vector(1, 0, 0), vector(0, 1, 0)) });
    var p = [];
    for (var i = 0; i < size(pts); i += 1) p = append(p, pts[i] * millimeter);
    p = append(p, pts[0] * millimeter);
    skPolyline(sk, "poly", { "points" : p });
    skSolve(sk);
    opExtrude(context, id + "ex", { "entities" : qSketchRegion(id + "sk"), "direction" : vector(1, 0, 0), "endBound" : BoundingType.BLIND, "endDepth" : length * millimeter });
    return qCreatedBy(id + "ex", EntityType.BODY);
}
function unite(context is Context, id is Id, bodies is array) returns Query
{
    if (size(bodies) > 1) opBoolean(context, id, { "tools" : qUnion(bodies), "operationType" : BooleanOperationType.UNION });
    return qUnion(bodies);
}
function cut(context is Context, id is Id, target is Query, tools is array) returns Query
{
    opBoolean(context, id, { "targets" : target, "tools" : qUnion(tools), "operationType" : BooleanOperationType.SUBTRACTION });
    return target;
}
function nameColor(context is Context, body is Query, name is string, c is Color)
{
    setProperty(context, { "entities" : body, "propertyType" : PropertyType.NAME, "value" : name });
    setProperty(context, { "entities" : body, "propertyType" : PropertyType.APPEARANCE, "value" : c });
}
function errMarker(context is Context, id is Id, label is string, error, slot is number)
{
    fCuboid(context, id + ("err" ~ slot), { "corner1" : vector(-300, 300 + slot * 10, 0) * millimeter, "corner2" : vector(-295, 305 + slot * 10, 5) * millimeter });
    setProperty(context, { "entities" : qCreatedBy(id + ("err" ~ slot), EntityType.BODY), "propertyType" : PropertyType.NAME, "value" : "ERR " ~ label ~ ": " ~ toString(error) });
}
const BLACK = color(0.08, 0.08, 0.09);
const PURPLE = color(0.46, 0.17, 0.58);
const STEEL = color(0.62, 0.63, 0.66);
const ALU = color(0.80, 0.81, 0.83);
const TEMPLATE = color(0.95, 0.85, 0.20);

annotation { "Feature Type Name" : "Probe hood scoop system", "Feature Type Description" : "Rev C concept: hood-matched base frame, slab cowl, mouth bezel, throat sleeve, short flap guide, backing frame, hardware, fit-check template." }
export const probeHoodScoop = defineFeature(function(context is Context, id is Id, definition is map)
    precondition
    {
        annotation { "Group Name" : "Build", "Collapsed By Default" : false }
        {
            annotation { "Name" : "Fit-check template (print FIRST)", "Default" : true } definition.buildTemplate is boolean;
            annotation { "Name" : "Base frame (hood-matched)", "Default" : true } definition.buildBase is boolean;
            annotation { "Name" : "One-piece body (merge base + cowl; prints roof-down)", "Default" : true } definition.onePiece is boolean;
            annotation { "Name" : "Throat sleeve as separate part", "Default" : true } definition.buildSleeve is boolean;
            annotation { "Name" : "Cowl slab", "Default" : true } definition.buildCowl is boolean;
            annotation { "Name" : "Mouth bezel", "Default" : true } definition.buildBezel is boolean;
            annotation { "Name" : "Lower guide flap (PROVISIONAL)", "Default" : true } definition.buildGuide is boolean;
            annotation { "Name" : "Rain cap (snap-in mouth blank)", "Default" : true } definition.buildRainCap is boolean;
            annotation { "Name" : "Metal backing strips (25 mm flat bar)", "Default" : true } definition.buildBacking is boolean;
            annotation { "Name" : "Hardware (bolts, tubes, nuts)", "Default" : true } definition.buildHardware is boolean;
            annotation { "Name" : "Place on scan site (off = flat at origin for export)", "Default" : true } definition.placeOnScan is boolean;
            annotation { "Name" : "Show tool-access envelopes (socket above nuts, hex key below heads)", "Default" : true } definition.showToolAccess is boolean;
        }
        annotation { "Group Name" : "Hood opening (proposed cut, not measured)", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Clear throat width" } isLength(definition.cutW, { (millimeter) : [100, 195, 300] } as LengthBoundSpec);
            annotation { "Name" : "Clear throat length (fore-aft)" } isLength(definition.cutL, { (millimeter) : [40, 71, 150] } as LengthBoundSpec);
            annotation { "Name" : "Throat corner radius" } isLength(definition.cutR, { (millimeter) : [2, 10, 30] } as LengthBoundSpec);
            annotation { "Name" : "Throat sleeve through both skins", "Default" : true } definition.sleeve is boolean;
            annotation { "Name" : "Sleeve wall" } isLength(definition.sleeveWall, { (millimeter) : [1.2, 2, 4] } as LengthBoundSpec);
        }
        annotation { "Group Name" : "Hood stack (MEASURE at pilot hole)", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Outer skin thickness" } isLength(definition.skinT, { (millimeter) : [0.5, 0.8, 2] } as LengthBoundSpec);
            annotation { "Name" : "Gap to inner panel (scan hint 21)" } isLength(definition.innerGap, { (millimeter) : [0, 21, 60] } as LengthBoundSpec);
            annotation { "Name" : "Inner panel thickness" } isLength(definition.innerT, { (millimeter) : [0, 0.8, 2] } as LengthBoundSpec);
            annotation { "Name" : "Gasket compressed" } isLength(definition.gasketT, { (millimeter) : [0, 1.5, 4] } as LengthBoundSpec);
        }
        annotation { "Group Name" : "Base frame", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Base width (P1S bed 256)" } isLength(definition.baseW, { (millimeter) : [150, 244, 254] } as LengthBoundSpec);
            annotation { "Name" : "Base front edge (-y)" } isLength(definition.baseFront, { (millimeter) : [40, 97, 150] } as LengthBoundSpec);
            annotation { "Name" : "Base rear edge (+y)" } isLength(definition.baseRear, { (millimeter) : [40, 84, 150] } as LengthBoundSpec);
            annotation { "Name" : "Base corner radius" } isLength(definition.baseR, { (millimeter) : [2, 10, 30] } as LengthBoundSpec);
            annotation { "Name" : "Base thickness" } isLength(definition.baseT, { (millimeter) : [4, 6, 12] } as LengthBoundSpec);
        }
        annotation { "Group Name" : "Cowl", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Cowl width" } isLength(definition.bodyW, { (millimeter) : [150, 196, 240] } as LengthBoundSpec);
            annotation { "Name" : "Cowl front edge (-y)" } isLength(definition.bodyFront, { (millimeter) : [30, 65, 120] } as LengthBoundSpec);
            annotation { "Name" : "Cowl rear edge / tail (+y)" } isLength(definition.bodyRear, { (millimeter) : [40, 60, 140] } as LengthBoundSpec);
            annotation { "Name" : "Cowl top height above hood" } isLength(definition.roofTop, { (millimeter) : [40, 72, 100] } as LengthBoundSpec);
            annotation { "Name" : "Wall / roof thickness" } isLength(definition.wall, { (millimeter) : [2, 3, 5] } as LengthBoundSpec);
            annotation { "Name" : "Vertical corner radius" } isLength(definition.bodyR, { (millimeter) : [1, 4, 15] } as LengthBoundSpec);
            annotation { "Name" : "Front brow chamfer" } isLength(definition.chamferF, { (millimeter) : [0, 4, 40] } as LengthBoundSpec);
            annotation { "Name" : "Rear chamfer" } isLength(definition.chamferR, { (millimeter) : [0, 10, 40] } as LengthBoundSpec);
            annotation { "Name" : "Mouth clear width" } isLength(definition.mouthW, { (millimeter) : [100, 186, 230] } as LengthBoundSpec);
            annotation { "Name" : "Mouth corner radius" } isLength(definition.mouthR, { (millimeter) : [1, 4, 15] } as LengthBoundSpec);
            annotation { "Name" : "Mouth inner lip radius (aero)" } isLength(definition.lipR, { (millimeter) : [0, 2.5, 6] } as LengthBoundSpec);
            annotation { "Name" : "Bezel width" } isLength(definition.bezelW, { (millimeter) : [3, 5, 12] } as LengthBoundSpec);
        }
        annotation { "Group Name" : "Fasteners (M6)", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Bolt x offset (side rows)" } isLength(definition.boltX, { (millimeter) : [60, 112, 130] } as LengthBoundSpec);
            annotation { "Name" : "Front row y" } isLength(definition.boltYF, { (millimeter) : [40, 80, 140] } as LengthBoundSpec);
            annotation { "Name" : "Middle row y (+ = rearward)" } isLength(definition.boltYM, { (millimeter) : [-60, -4, 60] } as LengthBoundSpec);
            annotation { "Name" : "Rear row y" } isLength(definition.boltYR, { (millimeter) : [40, 72, 140] } as LengthBoundSpec);
            annotation { "Name" : "Clearance hole" } isLength(definition.holeD, { (millimeter) : [5, 6.5, 8] } as LengthBoundSpec);
            annotation { "Name" : "Bolt length (M6 x ...)" } isLength(definition.boltL, { (millimeter) : [20, 50, 80] } as LengthBoundSpec);
            annotation { "Name" : "Backing plate thickness" } isLength(definition.backingT, { (millimeter) : [1, 3, 4] } as LengthBoundSpec);
        }
        annotation { "Group Name" : "Lower guide (physical-fit parameters)", "Collapsed By Default" : true }
        {
            annotation { "Name" : "Flap width" } isLength(definition.guideW, { (millimeter) : [100, 200, 240] } as LengthBoundSpec);
            annotation { "Name" : "Flap reach" } isLength(definition.guideReach, { (millimeter) : [10, 50, 150] } as LengthBoundSpec);
            annotation { "Name" : "Flap angle below hood" } isAngle(definition.guideAngle, { (degree) : [10, 45, 80] } as AngleBoundSpec);
            annotation { "Name" : "Inboard cheek height" } isLength(definition.cheekH, { (millimeter) : [0, 55, 120] } as LengthBoundSpec);
            annotation { "Name" : "Guide plate thickness" } isLength(definition.guideT, { (millimeter) : [2, 3, 5] } as LengthBoundSpec);
        }
    }
    {
        try
        {
        const mm = millimeter;
        const cutW = definition.cutW / mm; const cutL = definition.cutL / mm; const cutR = definition.cutR / mm;
        const sw = definition.sleeve ? definition.sleeveWall / mm : 0;
        const holeW = cutW + 2 * sw; const holeL = cutL + 2 * sw; const holeR = cutR + sw;     // actual hood cut if sleeve is used
        const skinT = definition.skinT / mm; const gap = definition.innerGap / mm; const innerT = definition.innerT / mm; const gk = definition.gasketT / mm;
        const stackBottom = -(gk + skinT + gap + innerT);                                       // underside of inner panel (z), local
        const baseW = definition.baseW / mm; const bF = -definition.baseFront / mm; const bR = definition.baseRear / mm; const baseR = definition.baseR / mm; const baseT = definition.baseT / mm;
        const baseCy = (bF + bR) / 2; const baseL = bR - bF;
        const bodyW = definition.bodyW / mm; const yF = -definition.bodyFront / mm; const yR = definition.bodyRear / mm; const top = definition.roofTop / mm; const w = definition.wall / mm; const bodyR = definition.bodyR / mm;
        const chF = definition.chamferF / mm; const chR = definition.chamferR / mm; const mouthW = definition.mouthW / mm; const mouthR = definition.mouthR / mm; const lipR = definition.lipR / mm; const bzW = definition.bezelW / mm;
        const bx = definition.boltX / mm; const yf = -definition.boltYF / mm; const ym = definition.boltYM / mm; const yr = definition.boltYR / mm; const holeD = definition.holeD / mm; const boltL = definition.boltL / mm; const bkT = definition.backingT / mm;
        const bolts = [[-bx, yf], [bx, yf], [-bx, ym], [bx, ym], [-bx, yr], [bx, yr], [0, yf], [0, yr]];
        const guideW = definition.guideW / mm; const reach = definition.guideReach / mm; const ang = definition.guideAngle; const cheekH = definition.cheekH / mm; const gt = definition.guideT / mm;
        const mouthH = top - chF - bzW - gk - baseT;                                                            // clear mouth height above sill (base top)
        const gTop = gk;                                                                            // gasket top = base underside datum (z=0 is hood outer skin at O)

        var all = [];
        var base;

        // ---------------- Part A: base frame (hood-matched underside via split by lofted sag surface) ----------------
        if (definition.buildBase)
        {
        try
        {
            base = rrBox(context, id + "base", 0, baseCy, baseW, baseL, gTop - 12, gTop + baseT, baseR);
            // lofted hood-sag surface (5 sections in y, 7-point splines in x), extended beyond the base outline
            var profiles = [];
            const ys = [bF - 15, bF + baseL * 0.25, baseCy, bR - baseL * 0.25, bR + 15];
            for (var i = 0; i < size(ys); i += 1)
            {
                const yi = ys[i];
                var sk = newSketchOnPlane(context, id + ("sag" ~ i), { "sketchPlane" : plane(vector(0, yi, 0) * mm, vector(0, -1, 0), vector(1, 0, 0)) });
                var pts = [];
                for (var k = 0; k < 7; k += 1)
                {
                    const xk = -baseW / 2 - 15 + k * (baseW + 30) / 6;
                    pts = append(pts, vector(xk, gTop + sagZ(xk, yi)) * mm);
                }
                skFitSpline(sk, "spl", { "points" : pts });
                skSolve(sk);
                profiles = append(profiles, qCreatedBy(id + ("sag" ~ i), EntityType.EDGE));
            }
            opLoft(context, id + "sagLoft", { "profileSubqueries" : profiles, "bodyType" : ToolBodyType.SURFACE });
            const sagSurf = qCreatedBy(id + "sagLoft", EntityType.BODY);
            opSplitPart(context, id + "baseSplit", { "targets" : base, "tool" : sagSurf, "keepTools" : false });
            // keep the upper piece: the body containing a point just below the base top at the centre-front bar
            const keep = qContainsPoint(qCreatedBy(id + "base", EntityType.BODY), vector(0, bF + 6, gTop + baseT - 1) * mm);
            opDeleteBodies(context, id + "baseDrop", { "entities" : qSubtraction(qCreatedBy(id + "base", EntityType.BODY), keep) });
            base = keep;
            var tools = [];
            // throat opening through base
            tools = append(tools, rrBox(context, id + "baseCut", 0, 0, cutW, cutL, gTop - 20, gTop + baseT + 10, cutR));
            for (var i = 0; i < size(bolts); i += 1)
                tools = append(tools, cylZ(context, id + ("bh" ~ i), bolts[i][0], bolts[i][1], gTop - 20, gTop + baseT + 10, holeD));
            cut(context, id + "baseCuts", base, tools);
            var adds = [];
            // raised bolt pads (TE detail) and the locating curb for the cowl skirt
            // TE detail that prints on the bed face: 0.6 mm debossed ring around each bolt (no protrusions on the top face)
            var rings = [];
            for (var i = 0; i < size(bolts); i += 1)
            {
                var rg = cylZ(context, id + ("ring" ~ i), bolts[i][0], bolts[i][1], gTop + baseT - 0.6, gTop + baseT + 1, 14);
                cut(context, id + ("ringc" ~ i), rg, [cylZ(context, id + ("ringci" ~ i), bolts[i][0], bolts[i][1], gTop + baseT - 2, gTop + baseT + 2, 11)]);
                rings = append(rings, rg);
            }
            cut(context, id + "ringCuts", base, rings);
            if (definition.buildSleeve)
                cut(context, id + "sleeveSeat", base, [rrBox(context, id + "sleeveSeatB", 0, 0, holeW + 0.4, holeL + 0.4, gTop - 2, gTop + 1.5, holeR)]);
            if (!definition.onePiece)
            {
            var curb = rrBox(context, id + "curb", 0, (yF + yR) / 2, bodyW - 2 * w - 0.6, (yR - yF) - 2 * w - 0.6, gTop + baseT, gTop + baseT + 3, max(bodyR - w, 1));
            cut(context, id + "curbIn", curb, [rrBox(context, id + "curbInner", 0, (yF + yR) / 2, bodyW - 2 * w - 6.6, (yR - yF) - 2 * w - 6.6, gTop + baseT - 1, gTop + baseT + 5, max(bodyR - w - 3, 1))]);
            // open the curb at the mouth so the sill is just the base top
            cut(context, id + "curbMouth", curb, [mkBox(context, id + "curbMouthB", -mouthW / 2, yF - 1, gTop + baseT - 1, mouthW / 2, yF + w + 4, gTop + baseT + 5)]);
            adds = append(adds, curb);
            }
            if (size(adds) > 0) base = unite(context, id + "baseU", concatenateArrays([[base], adds]));
            // soften the throat top edge (entrance from the scoop chamber into the hood)
            try silent { opFillet(context, id + "throatLip", { "entities" : qIntersection([qOwnedByBody(base, EntityType.EDGE), qContainsPoint(qOwnedByBody(base, EntityType.EDGE), vector(0, -cutL / 2, gTop + baseT) * mm)]), "radius" : 2 * mm }); }
            if (!definition.onePiece) { nameColor(context, base, "A base frame (hood-matched)", BLACK); all = append(all, base); }
        }
        catch (error) { errMarker(context, id, "BASE", error, 1); }
        }

        // ---------------- Part B: cowl slab ----------------
        if (definition.buildCowl)
        {
            const z0 = gTop + baseT;
            var cowl = rrBox(context, id + "cowl", 0, (yF + yR) / 2, bodyW, yR - yF, z0, top, bodyR);
            // 45-degree brow/tail chamfers as boolean wedge cuts (robust against the corner fillets)
            try
            {
                var wedges = [];
                if (chF > 0) wedges = append(wedges, wedgeX(context, id + "wF", -bodyW / 2 - 2, bodyW + 4, [vector(yF - 2, top - chF - 2), vector(yF + chF + 2, top + 2), vector(yF - 2, top + 2)]));
                if (chR > 0) wedges = append(wedges, wedgeX(context, id + "wR", -bodyW / 2 - 2, bodyW + 4, [vector(yR + 2, top - chR - 2), vector(yR - chR - 2, top + 2), vector(yR + 2, top + 2)]));
                if (size(wedges) > 0) cut(context, id + "chamfers", cowl, wedges);
            }
            catch (error) { errMarker(context, id, "COWL chamfers", error, 8); }
            var tools = [];
            try
            {
                var cav = rrBox(context, id + "cowlIn", 0, (yF + yR) / 2, bodyW - 2 * w, (yR - yF) - 2 * w, z0 - 1, top - w, max(bodyR - w, 0.5));
                const wo = w * 1.4142;
                var cw = [];
                if (chF > 0) cw = append(cw, wedgeX(context, id + "cwF", -bodyW / 2 - 2, bodyW + 4, [vector(yF - 2, top - chF - wo - 2), vector(yF + chF + wo + 2, top + 2), vector(yF - 2, top + 2)]));
                if (chR > 0) cw = append(cw, wedgeX(context, id + "cwR", -bodyW / 2 - 2, bodyW + 4, [vector(yR + 2, top - chR - wo - 2), vector(yR - chR - wo - 2, top + 2), vector(yR + 2, top + 2)]));
                if (size(cw) > 0) cut(context, id + "cavCh", cav, cw);
                tools = append(tools, cav);
                var mouth = mkBox(context, id + "mouth", -mouthW / 2, yF - 5, z0, mouthW / 2, yF + w + 2, z0 + mouthH);
                filletDir(context, id + "mouthR", mouth, vector(0, 1, 0), mouthR);
                tools = append(tools, mouth);
                var rebate = mkBox(context, id + "rebate", -mouthW / 2 - bzW, yF - 5, z0 - 0.01, mouthW / 2 + bzW, yF + 3, z0 + mouthH + bzW);
                filletDir(context, id + "rebateR", rebate, vector(0, 1, 0), mouthR + bzW);
                tools = append(tools, rebate);
            }
            catch (error) { errMarker(context, id, "COWL cutters", error, 10); }
            try { cut(context, id + "cowlCuts", cowl, tools); }
            catch (error) { errMarker(context, id, "COWL cut", error, 11); }
            if (lipR > 0) try silent { opFillet(context, id + "lip", { "entities" : qIntersection([qParallelEdges(qOwnedByBody(cowl, EntityType.EDGE), vector(1, 0, 0)), qContainsPoint(qOwnedByBody(cowl, EntityType.EDGE), vector(0, yF + w + 2, z0 + mouthH) * mm)]), "radius" : lipR * mm }); }
            // debossed 4OGS wordmark on the roof (0.6 mm; reads correctly standing in front of the car). Pause-and-swap to purple at layer 3 when printing roof-down.
            try
            {
                const lc = vector(0, (yF + chF + yR - chR) / 2) * mm;
                var lsk = newSketchOnPlane(context, id + "logoSk", { "sketchPlane" : plane(vector(0, 0, top) * mm, vector(0, 0, 1), vector(1, 0, 0)) });
                skPolyline(lsk, "lp0", { "points" : [vector(-21.351, 0.598) * mm + lc, vector(-26.959, -16.941) * mm + lc, vector(-13.285, -16.941) * mm + lc, vector(-9.108, -13.926) * mm + lc, vector(-1.844, 8.798) * mm + lc, vector(-16.300, 8.798) * mm + lc, vector(-19.459, 6.518) * mm + lc, vector(-20.659, 2.763) * mm + lc, vector(-10.505, 2.763) * mm + lc, vector(-14.874, -10.906) * mm + lc, vector(-18.297, -10.906) * mm + lc, vector(-14.620, 0.598) * mm + lc, vector(-21.351, 0.598) * mm + lc] });
                skPolyline(lsk, "lp1", { "points" : [vector(-29.700, 16.941) * mm + lc, vector(-37.555, 16.941) * mm + lc, vector(-42.087, 2.763) * mm + lc, vector(-34.232, 2.763) * mm + lc, vector(-29.700, 16.941) * mm + lc] });
                skPolyline(lsk, "lp2", { "points" : [vector(14.663, 0.598) * mm + lc, vector(17.284, 8.798) * mm + lc, vector(2.823, 8.798) * mm + lc, vector(-0.336, 6.518) * mm + lc, vector(-1.536, 2.763) * mm + lc, vector(8.623, 2.763) * mm + lc, vector(7.927, 0.598) * mm + lc, vector(14.663, 0.598) * mm + lc] });
                skPolyline(lsk, "lp3", { "points" : [vector(46.000, 16.941) * mm + lc, vector(-26.224, 16.941) * mm + lc, vector(-32.422, -2.432) * mm + lc, vector(-35.898, -2.432) * mm + lc, vector(-34.929, 0.598) * mm + lc, vector(-42.783, 0.598) * mm + lc, vector(-46.000, -9.470) * mm + lc, vector(-34.669, -9.470) * mm + lc, vector(-37.060, -16.941) * mm + lc, vector(-29.201, -16.941) * mm + lc, vector(-20.333, 10.805) * mm + lc, vector(39.307, 10.805) * mm + lc, vector(36.734, 2.763) * mm + lc, vector(46.000, 16.941) * mm + lc] });
                skPolyline(lsk, "lp4", { "points" : [vector(18.801, 6.518) * mm + lc, vector(17.601, 2.763) * mm + lc, vector(34.492, 2.763) * mm + lc, vector(36.417, 8.798) * mm + lc, vector(21.961, 8.798) * mm + lc, vector(18.801, 6.518) * mm + lc] });
                skPolyline(lsk, "lp5", { "points" : [vector(23.641, 0.598) * mm + lc, vector(16.910, 0.598) * mm + lc, vector(14.452, -7.079) * mm + lc, vector(24.611, -7.079) * mm + lc, vector(23.386, -10.906) * mm + lc, vector(13.232, -10.906) * mm + lc, vector(11.302, -16.941) * mm + lc, vector(28.188, -16.941) * mm + lc, vector(33.267, -1.063) * mm + lc, vector(23.108, -1.063) * mm + lc, vector(23.641, 0.598) * mm + lc] });
                skPolyline(lsk, "lp6", { "points" : [vector(-6.851, -13.859) * mm + lc, vector(-3.999, -16.941) * mm + lc, vector(9.055, -16.941) * mm + lc, vector(13.117, -4.227) * mm + lc, vector(5.209, -4.227) * mm + lc, vector(3.951, -8.160) * mm + lc, vector(5.128, -8.160) * mm + lc, vector(4.249, -10.906) * mm + lc, vector(0.826, -10.906) * mm + lc, vector(4.508, 0.598) * mm + lc, vector(-2.228, 0.598) * mm + lc, vector(-6.851, -13.859) * mm + lc] });
                skSolve(lsk);
                opExtrude(context, id + "logoEx", { "entities" : qSketchRegion(id + "logoSk"), "direction" : vector(0, 0, -1), "endBound" : BoundingType.BLIND, "endDepth" : 0.6 * mm });
                cut(context, id + "logoCut", cowl, [qCreatedBy(id + "logoEx", EntityType.BODY)]);
            }
            catch (error) { errMarker(context, id, "COWL logo", error, 12); }
            try
            {
                if (definition.onePiece && definition.buildBase)
                {
                    opBoolean(context, id + "bodyU", { "tools" : qUnion([base, cowl]), "operationType" : BooleanOperationType.UNION });
                    nameColor(context, base, "A body: flange + cowl, one piece (black ASA, print roof-down)", BLACK); all = append(all, base);
                }
                else { nameColor(context, cowl, "B cowl slab", BLACK); all = append(all, cowl); }
            }
            catch (error) { errMarker(context, id, "COWL name/merge", error, 13); }
            if (definition.buildBezel)
            {
                try
                {
                    var bz = mkBox(context, id + "bz", -mouthW / 2 - bzW, yF, z0, mouthW / 2 + bzW, yF + 3, z0 + mouthH + bzW);
                    filletDir(context, id + "bzR", bz, vector(0, 1, 0), mouthR + bzW);
                    var bzi = mkBox(context, id + "bzi", -mouthW / 2, yF - 2, z0 - 1, mouthW / 2, yF + 5, z0 + mouthH);
                    filletDir(context, id + "bziR", bzi, vector(0, 1, 0), mouthR);
                    cut(context, id + "bzCut", bz, [bzi]);
                    nameColor(context, bz, "B2 mouth bezel (purple)", PURPLE);
                    all = append(all, bz);
                }
                catch (error) { errMarker(context, id, "BEZEL", error, 14); }
            }
        }

        // ---------------- Part S: throat sleeve / liner through both skins (purple), pushed up from below into the body's 1.5 mm seat; 2 mm drip lip below the strips ----------------
        if (definition.buildSleeve && definition.sleeve)
        {
            try
            {
                const zTopS = gTop + 1.5 - 0.2; const zBotS = stackBottom - bkT;
                var sl = rrBox(context, id + "sleeve", 0, 0, holeW, holeL, zBotS, zTopS, holeR);
                cut(context, id + "sleeveIn", sl, [rrBox(context, id + "sleeveInner", 0, 0, cutW, cutL, zBotS - 2, zTopS + 2, cutR)]);
                nameColor(context, sl, "S throat sleeve / liner (purple ASA, install from below, ends flush with strips)", PURPLE);
                all = append(all, sl);
            }
            catch (error) { errMarker(context, id, "SLEEVE", error, 16); }
        }

        // ---------------- Part R: rain cap (snap-in blank for the mouth; shown exploded 45 mm ahead of the mouth) ----------------
        if (definition.buildRainCap && definition.buildCowl)
        {
            try
            {
                const z0 = gTop + baseT; const ey = -45;                                              // explode offset (-y) for visibility
                var capF = mkBox(context, id + "capF", -mouthW / 2 - bzW, yF + ey - 3, z0, mouthW / 2 + bzW, yF + ey, z0 + mouthH + bzW);
                filletDir(context, id + "capFR", capF, vector(0, 1, 0), mouthR + bzW);
                var plug = mkBox(context, id + "plug", -mouthW / 2 + 0.3, yF + ey - 0.5, z0 + 0.3, mouthW / 2 - 0.3, yF + ey + 15, z0 + mouthH - 0.3);
                filletDir(context, id + "plugR", plug, vector(0, 1, 0), max(mouthR - 0.3, 0.5));
                // hollow the plug (3 mm shell) so it prints light and flexes to snap
                var plugIn = mkBox(context, id + "plugIn", -mouthW / 2 + 3.3, yF + ey + 3, z0 + 3.3, mouthW / 2 - 3.3, yF + ey + 16, z0 + mouthH - 3.3);
                cut(context, id + "plugHollow", plug, [plugIn]);
                // two snap bumps (0.6 mm) on the plug top, 12 mm in, engage behind the inner lip
                var bumps = [];
                for (var k = 0; k < 2; k += 1)
                    bumps = append(bumps, mkBox(context, id + ("bump" ~ k), (k == 0 ? -1 : 1) * mouthW / 4 - 10, yF + ey + 9, z0 + mouthH - 0.4, (k == 0 ? -1 : 1) * mouthW / 4 + 10, yF + ey + 12, z0 + mouthH + 0.3));
                // finger notch in the flange bottom edge
                var notch = mkBox(context, id + "notch", -15, yF + ey - 4, z0 - 1, 15, yF + ey + 1, z0 + 4);
                var cap = unite(context, id + "capU", concatenateArrays([[capF, plug], bumps]));
                cut(context, id + "capNotch", cap, [notch]);
                nameColor(context, cap, "R rain cap (purple, snap-in blank)", PURPLE);
                all = append(all, cap);
            }
            catch (error) { errMarker(context, id, "RAINCAP", error, 15); }
        }

        // ---------------- Part C: lower guide — U-bracket (two side arms + rear bar) clamped UNDER the side backing strips by the middle-row bolt heads, flap at the rear ----------------
        const zPlateTop = stackBottom - bkT - 0.5;                                                 // just under the strips
        const armHalfW = bx + 13;                                                                  // arms reach the middle-row bolts at x = ±bx
        const hy = holeL / 2 + 24;                                                                 // hinge line (rear bar outer edge)
        if (definition.buildGuide)
        {
        try
        {
            var plate = rrBox(context, id + "gU", 0, (hy - 22) / 2, 2 * armHalfW, hy + 22, zPlateTop - gt, zPlateTop, 6);   // y from -22 to hy
            var utools = [rrBox(context, id + "gUin", 0, 0, holeW + 6, holeL + 6, zPlateTop - gt - 2, zPlateTop + 2, 12)];   // open around the sleeve
            utools = append(utools, mkBox(context, id + "gUfront", -(holeW / 2 + 3), -30, zPlateTop - gt - 2, holeW / 2 + 3, 0, zPlateTop + 2));   // open front
            for (var i = 2; i < 4; i += 1)                                                         // middle-row bolt clearance holes
                utools = append(utools, cylZ(context, id + ("gUh" ~ i), bolts[i][0], bolts[i][1], zPlateTop - gt - 2, zPlateTop + 2, holeD));
            cut(context, id + "gUcuts", plate, utools);
            var flap = mkBox(context, id + "flap", -guideW / 2, hy - 3, zPlateTop - gt, guideW / 2, hy + reach, zPlateTop);
            opTransform(context, id + "flapRot", { "bodies" : flap, "transform" : rotationAround(line(vector(0, hy, zPlateTop - gt) * mm, vector(1, 0, 0)), -ang) });
            var parts = [plate, flap];
            if (cheekH > 0)
            {
                const zt = zPlateTop;
                var csk = newSketchOnPlane(context, id + "cheekSk", { "sketchPlane" : plane(vector(-guideW / 2, 0, 0) * mm, vector(-1, 0, 0), vector(0, 1, 0)) });
                skPolyline(csk, "cheekPoly", { "points" : [vector(hy - 20, -(zt - gt + 0.5)) * mm, vector(hy + reach * cos(ang), -(zt - gt + 0.5)) * mm, vector(hy + reach * cos(ang), -(zt - gt - reach * sin(ang))) * mm, vector(hy - 20, -(zt - gt - cheekH)) * mm, vector(hy - 20, -(zt - gt + 0.5)) * mm] });
                skSolve(csk);
                opExtrude(context, id + "cheekEx", { "entities" : qSketchRegion(id + "cheekSk"), "direction" : vector(1, 0, 0), "endBound" : BoundingType.BLIND, "endDepth" : gt * mm });
                parts = append(parts, qCreatedBy(id + "cheekEx", EntityType.BODY));
            }
            var guide = unite(context, id + "guideU", parts);
            nameColor(context, guide, "C lower guide: U-bracket + flap (PROVISIONAL, purple ASA, prints bracket-down, clamped by the 2 middle bolts)", PURPLE);
            all = append(all, guide);
        }
        catch (error) { errMarker(context, id, "GUIDE", error, 3); }
        }

        // ---------------- Part D: metal backing — 4 strips of 25 x 3 flat bar (2 cross strips with 3 holes, 2 side strips with bolt + 2 rivnut holes) ----------------
        if (definition.buildBacking)
        {
        try
        {
            const sw25 = 25;
            var strips = [];
            const cross = [[yf, "front"], [yr, "rear"]];
            for (var k = 0; k < 2; k += 1)
            {
                var st = rrBox(context, id + ("cs" ~ k), 0, cross[k][0], 2 * bx + sw25, sw25, stackBottom - bkT, stackBottom, 3);
                cut(context, id + ("csh" ~ k), st, [cylZ(context, id + ("csh0" ~ k), -bx, cross[k][0], stackBottom - bkT - 2, stackBottom + 2, holeD), cylZ(context, id + ("csh1" ~ k), 0, cross[k][0], stackBottom - bkT - 2, stackBottom + 2, holeD), cylZ(context, id + ("csh2" ~ k), bx, cross[k][0], stackBottom - bkT - 2, stackBottom + 2, holeD)]);
                nameColor(context, st, "D backing strip " ~ cross[k][1] ~ " 25x3 flat bar, L=" ~ (2 * bx + sw25) ~ " (3x Ø6.5)", ALU);
                strips = append(strips, st);
            }
            for (var k = 0; k < 2; k += 1)
            {
                const sx = (k == 0) ? -bx : bx;
                var st = rrBox(context, id + ("ss" ~ k), sx, ym, sw25, 110, stackBottom - bkT, stackBottom, 3);
                cut(context, id + ("ssh" ~ k), st, [cylZ(context, id + ("ssh0" ~ k), sx, ym, stackBottom - bkT - 2, stackBottom + 2, holeD)]);
                nameColor(context, st, "D backing strip side " ~ (k == 0 ? "L" : "R") ~ " 25x3 flat bar, L=110 (1x Ø6.5)", ALU);
                strips = append(strips, st);
            }
            all = concatenateArrays([all, strips]);
        }
        catch (error) { errMarker(context, id, "BACKING", error, 4); }
        }

        // ---------------- hardware (simplified): M6 button head BELOW the strip, shank up through strip/inner/gap/skin/gasket/flange, washer + nyloc on top ----------------
        if (definition.buildHardware)
        {
        try
        {
            for (var i = 0; i < size(bolts); i += 1)
            {
                const x = bolts[i][0]; const y = bolts[i][1];
                const guideHere = definition.buildGuide && (i == 2 || i == 3);
                const seat = stackBottom - bkT - (guideHere ? gt + 0.5 : 0);                       // head seats on the strip (or on the guide bracket under the strip)
                var head = cylZ(context, id + ("head" ~ i), x, y, seat - 3.3, seat, 10.5);          // ISO 7380 button head
                var bolt = cylZ(context, id + ("bolt" ~ i), x, y, seat, seat + boltL, 6.4);
                var lim = cylZ(context, id + ("lim" ~ i), x, y, gTop, gTop + baseT, 10);               // compression limiter tube through the printed flange
                cut(context, id + ("limc" ~ i), lim, [cylZ(context, id + ("limci" ~ i), x, y, gTop - 1, gTop + baseT + 1, 6.4)]);
                var spacer = cylZ(context, id + ("spc" ~ i), x, y, -(skinT + gap), -skinT, 10);         // spacer tube across the inter-skin gap (cut to measured length per hole)
                cut(context, id + ("spcc" ~ i), spacer, [cylZ(context, id + ("spcci" ~ i), x, y, -(skinT + gap) - 1, -skinT + 1, 6.4)]);
                var washer = cylZ(context, id + ("wsh" ~ i), x, y, gTop + baseT, gTop + baseT + 1.6, 12);
                cut(context, id + ("wshc" ~ i), washer, [cylZ(context, id + ("wshci" ~ i), x, y, gTop + baseT - 1, gTop + baseT + 3, 6.4)]);
                var nut = cylZ(context, id + ("nut" ~ i), x, y, gTop + baseT + 1.6, gTop + baseT + 1.6 + 6, 10);   // M6 nyloc on top (TE: exposed hex)
                var hwb = unite(context, id + ("hwU" ~ i), [head, bolt, lim, spacer, washer, nut]);
                nameColor(context, hwb, "HW M6x" ~ boltL ~ " head-down stack " ~ (i + 1) ~ (guideHere ? " (clamps guide)" : ""), STEEL);
                all = append(all, hwb);
            }
        }
        catch (error) { errMarker(context, id, "HARDWARE", error, 6); }
        }

        // ---------------- tool-access envelopes (translucent): 3/8" socket Ø17 x 60 above each nut; hex key / driver Ø20 x 60 below each head ----------------
        if (definition.showToolAccess)
        {
        try
        {
            var env = [];
            for (var i = 0; i < size(bolts); i += 1)
            {
                const x = bolts[i][0]; const y = bolts[i][1];
                const guideHere = definition.buildGuide && (i == 2 || i == 3);
                const seat = stackBottom - bkT - (guideHere ? gt + 0.5 : 0);
                env = append(env, cylZ(context, id + ("sock" ~ i), x, y, gTop + baseT + 1.6, gTop + baseT + 1.6 + 60, 17));
                env = append(env, cylZ(context, id + ("hexk" ~ i), x, y, seat - 3.3 - 60, seat - 3.3, 20));
            }
            for (var i = 0; i < size(env); i += 1)
            {
                setProperty(context, { "entities" : env[i], "propertyType" : PropertyType.NAME, "value" : "X tool envelope " ~ (i + 1) ~ (i % 2 == 0 ? " (socket on nut)" : " (hex key on head)") });
                setProperty(context, { "entities" : env[i], "propertyType" : PropertyType.APPEARANCE, "value" : color(0.2, 0.8, 0.3, 0.35) });
            }
            all = concatenateArrays([all, env]);
        }
        catch (error) { errMarker(context, id, "TOOLACCESS", error, 18); }
        }

        // ---------------- fit-check template (flat, 2 mm; print first, tape to the underside) ----------------
        if (definition.buildTemplate)
        {
        try
        {
            const tz0 = (definition.placeOnScan) ? gTop + baseT + top + 40 : -60;                      // park it above the scoop when placed; beside when flat
            var tp = rrBox(context, id + "tpl", 0, baseCy, baseW, baseL, tz0, tz0 + 2, baseR);
            var tools = [rrBox(context, id + "tplCut", 0, 0, holeW, holeL, tz0 - 2, tz0 + 4, holeR)];
            for (var i = 0; i < size(bolts); i += 1) tools = append(tools, cylZ(context, id + ("tph" ~ i), bolts[i][0], bolts[i][1], tz0 - 2, tz0 + 4, holeD));
            // centre/axis slots at the throat edge midpoints, FRONT notch, 100 mm calibration holes
            tools = append(tools, mkBox(context, id + "axF", -1, -(holeL / 2) - 14, tz0 - 2, 1, -(holeL / 2) + 1, tz0 + 4));
            tools = append(tools, mkBox(context, id + "axR", -1, holeL / 2 - 1, tz0 - 2, 1, holeL / 2 + 14, tz0 + 4));
            tools = append(tools, mkBox(context, id + "axL", -(holeW / 2) - 14, -1, tz0 - 2, -(holeW / 2) + 1, 1, tz0 + 4));
            tools = append(tools, mkBox(context, id + "axRt", holeW / 2 - 1, -1, tz0 - 2, holeW / 2 + 14, 1, tz0 + 4));
            tools = append(tools, mkBox(context, id + "frontNotch", -6, bF - 1, tz0 - 2, 6, bF + 8, tz0 + 4));
            tools = append(tools, cylZ(context, id + "cal0", -50, bR - 10, tz0 - 2, tz0 + 4, 3));
            tools = append(tools, cylZ(context, id + "cal1", 50, bR - 10, tz0 - 2, tz0 + 4, 3));
            cut(context, id + "tplCuts", tp, tools);
            try silent
            {
                var lsk = newSketchOnPlane(context, id + "tplTxt", { "sketchPlane" : plane(vector(0, 0, tz0 + 2) * mm, vector(0, 0, 1), vector(1, 0, 0)) });
                skText(lsk, "l1", { "text" : "FRONT", "fontName" : "OpenSans-Bold.ttf", "firstCorner" : vector(-22, bF + 10) * mm, "secondCorner" : vector(22, bF + 18) * mm });
                skText(lsk, "l2", { "text" : "42 SCOOP TEMPLATE  PRELIMINARY  100mm between holes", "fontName" : "OpenSans-Regular.ttf", "firstCorner" : vector(-110, bR - 22) * mm, "secondCorner" : vector(110, bR - 16) * mm });
                skSolve(lsk);
                opExtrude(context, id + "tplTxtEx", { "entities" : qSketchRegion(id + "tplTxt"), "direction" : vector(0, 0, -1), "endBound" : BoundingType.BLIND, "endDepth" : 0.6 * mm });
                cut(context, id + "tplTxtCut", tp, [qCreatedBy(id + "tplTxtEx", EntityType.BODY)]);
            }
            nameColor(context, tp, "T fit-check template (flat, PRELIMINARY)", TEMPLATE);
            all = append(all, tp);
        }
        catch (error) { errMarker(context, id, "TEMPLATE", error, 5); }
        }

        // ---------------- place everything at the fitted scan site ----------------
        if (definition.placeOnScan && size(all) > 0)
            opTransform(context, id + "place", { "bodies" : qUnion(all), "transform" : transform(SITE_M, SITE_O) });
        }
        catch (error) { errMarker(context, id, "BODY", error, 7); }
    });
